# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c919b53383793d48135e8dada4bc7831bbe0cb8925a255069ce6b9dd3cd79c13fde6d0abdf270e34e759b646aca2f215e07683ed74da1804806c9b7fa41815ed

test:
  secret_key_base: bbada5bef590f81d161580e682a0556f1eaf85637c697c822542a93e54819d1dd64c94167fdef47cc7804bf44a6eece2a109aed7a17def2e4c22c44bf059068d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Settings['app.secret'] %>
